version: "3.8"
services:
  nginx:
    build:
      context: ./
      dockerfile: dockerfile-nginx
    container_name: nginx
    hostname: nginx
    environment:
      TZ: Asia/Tokyo
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./src/:/var/www/html/
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
      - nginx-log:/var/log/nginx
      # Let's EncryptでSSL化
      - /etc/letsencrypt:/etc/letsencrypt
volumes:
  nginx-log:
    driver: local